services:
  - type: web
    name: binance-tradingview-webhook-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.main:app --bind 0.0.0.0:$PORT
    plan: free
